### ISSUE TITLE
Extended results of neural net. 

### ISSUE THREAD

**Issue by kstawiski** [jpmml/openscoring#14]
Dear Villu,
Sorry to bother you again, but I'm struggling with another issue.
Is there a way to receive in the result or wherever details about evaluation of neural network? Like probabilities (end or on specific neuron)?
It would be very helpful to implement this details in my project and currently in the response I get only the class of prediction.
Thank you very much in advance. I really appreciate your work.
Konrad

**Comment by vruusmann** [comment]
Classification-type neural network models typically compute a class probability distribution along the way. You can query it by defining an appropriate `Output` element, and appending it to the `PMML/NeuralNetwork` element.

The following `Output` element should fit the neural network model that you shared with me in #13:
```
<Output>
	<OutputField name="probability_disease" feature="probability" value="Cancer"/>
	<OutputField name="probability_no_disease" feature="probability" value="Controls+Borderline"/>
</Output>
```

**Comment by vruusmann** [comment]
In principle, one should be able to query the "output value" of any neuron using the `entityId` output feature:
```
<Output>
    <OutputField name="output_value_of_neuron_21" feature="entityId" value="21"/>
</Output>
```

Unfortunately, this functionality is not yet implemented by the underlying JPMML-Evaluator library.

**Comment by kstawiski** [comment]
Thank you very much! It's all working now! I appreciate your help.
