### ISSUE TITLE
NetworkSecurityContext behaving differently on Linux vs. Windows

### ISSUE THREAD

**Issue by njagadeesh** [jpmml/openscoring#7]
Hi I deployed it on centos6.7 [64bit os] with Apache Tomcat/8.0.27. I have taken war from 1.2.8. but when I ran

curl -X PUT --data-binary @test.xml -H "Content-type: text/xml" http://localhost:8080/openscoring/model/justtest
received.
 l{                      
  "message" : "Forbidden"
}

But same setup on windows server is working. Is there any separate setting for linux?

**Comment by vruusmann** [comment]
Let's diagnose if it's a Linux networking configuration problem or an Openscoring configuration problem.

Currently, you deployed Openscoring WAR file (ie. the contents of the `openscoring-webapp` module) on Tomcat. If you deploy Openscoring as a standalone command-line application (ie. the contents of the `openscoring-server` module), do you still get HTTP 403 forbidden or not?

By default, the access control is implemented by `org.openscoring.service.NetworkSecurityContextFilter` request filter class. On activation, it logs the list of "trusted" network addresses. Also, a log message is emitted every time when a restricted REST API endpoint is invoked. Please scan your Tomcat log file for messages that start with `Local network addresses` or `Admin role (granted|denied) to network address ($address)`. What do they say?

**Comment by vruusmann** [comment]
Closing this issue as invalid, because it is triggered by user's configuration, and the user hasn't provided any extra information about it.
