### ISSUE TITLE
KMEANS Test : 

### ISSUE THREAD

**Issue by Robino** [jpmml/openscoring#8]
Hello,

I try to make a prediction with this values (
[kmeans_topredict.txt](https://github.com/jpmml/openscoring/files/68256/kmeans_topredict.txt)

[KMEANS.pmml.model.txt](https://github.com/jpmml/openscoring/files/68257/KMEANS.pmml.model.txt)

I launch the commands:
```
curl -X PUT --data-binary @kmeans.pmml -H "Content-type: text/xml" http://localho
st:8080/openscoring/model/kmeans
```
and to predict 
```
curl -X POST --data-binary @kmeans2.json -H "Content-type: application/json" http://sandbox:8080/openscoring/model/kmeans
```

and I have this error : do you have any idea ?
```xml
2015 8:50:20 AM org.openscoring.service.ModelResource evaluate
                                                                FINE: Evaluation request record-001 has prepared arguments: {field_0=ContinuousValue{opType=CONTINUOUS, dataType=DOUBLE, value=20.0}, field_1=ContinuousValue{opType=CONTINUOUS, dataType=DOUBLE, value=756.72}, field_2=ContinuousValue{opType=CONTINUOUS, dataType=DOUBLE, value=1500.0}, field_3=ContinuousValue{opType=CONTINUOUS, dataType=DOUBLE, value=5.0}}
                                                                                         Dec 21, 2015 8:50:20 AM org.openscoring.service.ModelResource doEvaluate
                                                   SEVERE: Failed to evaluate
                                                                             java.lang.UnsupportedOperationException
      	at java.util.Collections$1.remove(Collections.java:4684)

```

**Comment by vruusmann** [comment]
This is a known issue, which was fixed in commit 197babd326.

Apparently, you are running an outdated Openscoring version (ie. something older than `1.2.5`). The latest stable version has no problem scoring your sample data record:

```
{
  "id" : "record-001",
  "result" : {
    "_default" : "1"
  }
}
```

**Comment by Robino** [comment]
Perhaps my issue is not opened in the good repository. I try to do it working with the Docker. I have done this before to use it.

docker build -t jpmml/openscoring:latest github.com/jpmml/openscoring-docker



Thanks

**Comment by vruusmann** [comment]
Indeed, the Openscoring-Docker project is based on the `1.2.2` version, which suffers from the aforementioned issue.

You would need to open its `pom.xml` file in text editor, and update the `org.openscoring:openscoring-server` dependency (on line 39) from `1.2.2` to something more recent, such as `1.2.9`.

I don't think I will update Openscoring-Docker, Openscoring-Heroku and Openscoring-OpenShift projects anytime soon. They're more like "templates" for integrating the Openscoring REST web service with various cloud platforms (rather than actual products).

**Comment by Robino** [comment]
Thanks a lot !
